application/routes.py
from flask import Blueprint, render_template, request
from application.models import Post, User
from datetime import datetime

blueprint = Blueprint('routes', __name__)


@blueprint.route("/")
def index():

    # Pagination
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template('index.html', posts=posts, elapsed_time=elapsed_time, total_users=total_users, total_posts=total_posts, latest_user=latest_user)


# Below three functions should be moved to models.py
def total_users():
    return User.query.count()


def total_posts():
    return Post.query.count()


def latest_user():
    return User.query.order_by(User.date_joined.desc()).first().username


def elapsed_time(post):

    seconds = int(datetime.utcnow().strftime('%s')) - \
        int(post.date_posted.strftime('%s'))

    if seconds == 1:
        value = seconds
        unit_of_time = 'second'

    elif seconds < 60:
        value = seconds
        unit_of_time = 'seconds'

    elif seconds < 120:
        value = int(seconds / 60)
        unit_of_time = 'minute'

    elif seconds < 3600:
        value = int(seconds / 60)
        unit_of_time = 'minutes'

    elif seconds < 7200:
        value = int(seconds / 60 / 60)
        unit_of_time = 'hour'

    elif seconds < 86400:
        value = int(seconds / 60 / 60)
        unit_of_time = 'hours'

    elif seconds < 172800:
        value = int(seconds / 60 / 60 / 24)
        unit_of_time = 'day'

    else:  # Implied 2 or more days ago
        value = int(seconds / 60 / 60 / 24)
        unit_of_time = 'days'

    return f'{value} {unit_of_time} ago'


@blueprint.route("/user/<string:username>")
def user_posts(username):

    # Try to locate the user being queried
    user = User.query.filter_by(username=username).first_or_404()

    # Pagination
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template('user_posts.html', title=f'@{username}', posts=posts, user=user, elapsed_time=elapsed_time)

application/templates/create_post.html
{% extends "base.html" %}

<!-- CONTENT START -->
{% block content %}

<!-- POST -->
<article class="media content-section">

    </head>

    <body>

        <div class="w-100">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
            <span class="mr-1 secondary-colour font-weight-bold">@{{ current_user.username }}</span>

            <form method="POST">
                {{ form.hidden_tag() }}
                <fieldset class="form-group mb-0">

                    <!-- CONTENT -->
                    <div class="form-group mb-0 mt-2">

                        {% if form.content.errors %}
                        {{ form.content(class="form-control dark-form is-invalid input-form", rows="9", style="resize: none;", placeholder="Got something to say?", onkeyup="countChar(this, 300)", maxlength="300", autofocus=true) }}
                        {% else %}
                        {{ form.content(class="form-control dark-form input-form", rows="9", style="resize: none;", placeholder="Got something to say?", onkeyup="countChar(this, 300)", maxlength="300", autofocus=true) }}
                        {% endif %}

                        <small class="float-right mt-1" id="charNum">300 characters remaining</small>


                        {% for error in form.content.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}

                    </div>

                </fieldset>

                <!-- SUBMIT -->
                <div class="form-group mb-1">
                    {{form.submit(class="btn button btn-sm input-button") }}
                </div>

            </form>
        </div>
</article>

<!-- CONTENT END -->
{% endblock content %}

<!-- SIDEBAR START -->
{% block sidebar %}

<div class="col-md-5 d-none d-sm-block">
    <div class="content-section">
        <div class="align-middle mt-1">
            <h5 class="heading-title">Tip and tricks!</h5>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#3f3fff" class="bi bi-lightbulb mb-2" viewBox="0 0 16 16">
                <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z" />
            </svg>
        </div>
        <ul class="list-group">

            <!-- LINK #1 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Quisque sit amet quam et massa pulvinar elementum.
                </li>
            </a>

            <!-- LINK #2 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Mauris et turpis ornare, eleifend sem ac, auctor sem.
                </li>
            </a>

            <!-- LINK #3 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Vivamus ut mauris nec tortor semper fringilla scelerisque a diam.
                </li>
            </a>

        </ul>
        </p>
    </div>
</div>

<!-- SIDEBAR END -->
{% endblock sidebar %}

application/templates/edit_post.html
{% extends "base.html" %}

<!-- CONTENT START -->
{% block content %}

<!-- POST -->
<article class="media content-section">

    <div class="w-100">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <span class="mr-1 secondary-colour font-weight-bold">@{{ post.author.username }}</span>

        <small class="font-weight-light">{{ elapsed_time(post) }}</small>

        <!-- EDITED -->
        {% if post.edited %}
        <small class="font-weight-light">• Edited</small>
        {% endif %}


        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">

                <!-- CONTENT -->
                <div class="form-group mb-0 mt-2">

                    {% if form.content.errors %}
                    {{ form.content(class="form-control dark-form is-invalid input-form", rows="9", style="resize: none;", onkeyup="countChar(this, 300)", maxlength="300", autofocus=true) }}
                    {% else %}
                    {{ form.content(class="form-control dark-form input-form", rows="9", style="resize: none;", onkeyup="countChar(this, 300)", maxlength="300", autofocus=true, onfocus="var temp_value=this.value; this.value=''; this.value=temp_value") }}
                    {% endif %}

                    {% if chars_remaining == 1 %}
                    <small class="float-right mt-1" id="charNum">{{chars_remaining}} character remaining</small>
                    {% else %}
                    <small class="float-right mt-1" id="charNum">{{chars_remaining}} characters remaining</small>
                    {% endif %}

                    {% for error in form.content.errors %}
                    <small class="text-danger">{{ error }}</small>
                    {% endfor %}

                </div>

            </fieldset>

            <!-- UPDATE/DELETE -->
            <div class="form-group mb-1">
                <button type="button" class="btn btn-secondary btn-sm inner-radius" onclick="history.back(-1)">Go back</button>
                <button type="button" class="btn btn-danger btn-sm ml-2 float-right inner-radius" data-toggle="modal" data-target="#deleteModal">Delete</button>
                {{form.submit(class="btn button input-button btn-sm float-right", value="Update") }}
            </div>
        </form>

        <!-- MODAL -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content modal-background">
                    <div class="modal-header" style="border: none;">
                        <h5 class="modal-title high-emphasis font-weight-bold" id="deleteModalLabel">Delete Post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span class="high-emphasis" aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body pb-0 pt-0">
                        <p class="mb-0 high-emphasis">Are you sure you want to permanently delete this post?</p>
                    </div>
                    <div class="modal-footer" style="border: none">
                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No, take me back</button>
                        <form method="POST" action="{{ url_for('post.delete_post', post_id=post.id) }}">
                            <input class="btn btn-danger btn-sm" type="submit" value="Yes, delete this post">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

<!-- CONTENT END -->
{% endblock content %}

<!-- SIDEBAR START -->
{% block sidebar %}

<div class="col-md-5 d-none d-sm-block">
    <div class="content-section">
        <div class="align-middle mt-1">
            <h5 class="heading-title">Tip and tricks!</h5>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#3f3fff" class="bi bi-lightbulb mb-2" viewBox="0 0 16 16">
                <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z" />
            </svg>
        </div>
        <ul class="list-group">

            <!-- LINK #1 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Quisque sit amet quam et massa pulvinar elementum.
                </li>
            </a>

            <!-- LINK #2 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Mauris et turpis ornare, eleifend sem ac, auctor sem.
                </li>
            </a>

            <!-- LINK #3 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Vivamus ut mauris nec tortor semper fringilla scelerisque a diam.
                </li>
            </a>

        </ul>
        </p>
    </div>
</div>

<!-- SIDEBAR END -->
{% endblock sidebar %}

application/templates/index.html
{% extends "base.html" %}

<!-- CONTENT START -->
{% block content %}

<!-- POSTS -->
{% for post in posts.items %}
<article class="media content-section">

    <div class="w-100">

        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">

        <span class="mr-1 secondary-colour font-weight-bold">@{{ post.author.username }}</span>

        <small class="font-weight-light">{{ elapsed_time(post) }}</small>

        <!-- EDITED -->
        {% if post.edited %}
        <small class="font-weight-light">• Edited</small>
        {% endif %}

        {% if post.author == current_user %}
        <p class="post-content mb-0 mt-2">{{ post.content }}</p>
        <div class="float-right">
            <small class="mb-0">
                <a href="{{ url_for('post.edit_post', post_id=post.id) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" class="bi bi-pencil-fill" viewBox="0 0 16 16" id="svg-edit">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                    </svg>
                </a>
            </small>
        </div>
        {% else %}
        <p class="post-content mt-2">{{ post.content }}</p>
        {% endif %}
    </div>

</article>
{% endfor %}

<!-- PAGINATION -->

<!-- PREVIOUS -->
{% for page_num in posts.iter_pages(left_edge=0, right_edge=0, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page > page_num %}
<a class="soft-primary-colour float-left mb-3" href="{{ url_for('routes.index', page=page_num) }}">
    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="var(--soft-primary)" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
        <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
    </svg>
    <small class="soft-primary-colour">Previous page</small>
</a>
{% endif %}
{% endif %}
{% endfor %}

<!-- NEXT -->
{% for page_num in posts.iter_pages(left_edge=0, right_edge=0, left_current=1, right_current=2) %}
{% if page_num and page_num > posts.page %}
{% if page_num > posts.page %}
<a class="soft-primary-colour float-right mb-3" href="{{ url_for('routes.index', page=page_num) }}">
    <small class="soft-primary-colour">Next page</small>
    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="var(--soft-primary)" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z" />
        <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z" />
    </svg>
</a>
{% endif %}
{% endif %}
{% endfor %}

<!-- CONTENT END -->
{% endblock content %}

<!-- SIDEBAR START -->
{% block sidebar %}

<div class="col-md-5">
    <div class="content-section">
        <div class="align-middle mt-1">
            <h5 class="heading-title">Dashboard</h5>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#3f3fff" class="bi bi-bar-chart-fill mb-2" viewBox="0 0 16 16">
                <path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z" />
            </svg>
        </div>
        <ul class="list-group">

            <!-- TOTAL USERS -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Total number of users
                    <span class="badge badge-pill badge-fill high-emphasis">{{ total_users() }}</span>
                </li>
            </a>

            <!-- TOTAL POSTS -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Total number of posts
                    <span class="badge badge-pill badge-fill high-emphasis">{{ total_posts() }}</span>
                </li>
            </a>

            <!-- LATEST USER -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Latest user
                    <span class="badge badge-pill badge-fill high-emphasis">@{{ latest_user() }}</span>
                </li>
            </a>

        </ul>
        </p>
    </div>
</div>

<!-- SIDEBAR END -->
{% endblock sidebar %}

application/templates/reset_request.html
{% extends "base.html" %}

<!-- CONTENT START -->
{% block content %}

<!-- RESET PASSWORD -->
<div class="content-section mb-2">
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">

            <!-- EMAIL -->
            <div class="form-group">

                {{ form.email.label(class="form-control-label font-weight-bold") }}

                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text dark-form">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z" />
                            </svg>
                        </div>
                    </div>

                    {% if form.email.errors %}
                    {{ form.email(class="form-control dark-form is-invalid input-form icon-field", autofocus=true, type="email") }}
                    {% else %}
                    {{ form.email(class="form-control dark-form input-form icon-field", autofocus=true, type="email") }}
                    {% endif %}

                </div>

                {% for error in form.email.errors %}
                <small class="text-danger">{{ error }}</small>
                {% endfor %}

            </div>

        </fieldset>

        <!-- SUBMIT -->
        <div class="form-group mb-1">
            {{form.submit(class="btn button input-button") }}
        </div>

    </form>
</div>

<!-- CONTENT END -->
{% endblock content %}

<!-- SIDEBAR START -->
{% block sidebar %}

<div class="col-md-5 d-none d-md-block">
    <img src="/static/img/password_reset.svg" alt="Log in image" class="img-fluid float-right pr-4">
</div>

<!-- SIDEBAR END -->
{% endblock sidebar %}

application/templates/user_posts.html
{% extends "base.html" %}

<!-- CONTENT START -->
{% block content %}

<!-- POSTS -->
{% for post in posts.items %}
<article class="media content-section">

    <div class="w-100">

        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">

        <a class="mr-1 secondary-colour font-weight-bold post-username" href="{{ url_for('routes.user_posts', username=post.author.username) }}">@{{ post.author.username }}</a>

        <small class="font-weight-light">{{ elapsed_time(post) }}</small>

        <!-- EDITED -->
        {% if post.edited %}
        <small class="font-weight-light">• Edited</small>
        {% endif %}

        {% if post.author == current_user %}
        <p class="post-content mb-0 mt-2">{{ post.content }}</p>
        <div class="float-right">
            <small class="mb-0">
                <a href="{{ url_for('post.edit_post', post_id=post.id) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" class="bi bi-pencil-fill" viewBox="0 0 16 16" id="svg-edit">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                    </svg>
                </a>
            </small>
        </div>
        {% else %}
        <p class="post-content mt-2">{{ post.content }}</p>
        {% endif %}
    </div>

</article>
{% endfor %}

<!-- PAGINATION -->

<!-- PREVIOUS -->
{% for page_num in posts.iter_pages(left_edge=0, right_edge=0, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page > page_num %}
<a class="soft-primary-colour float-left mb-3" href="{{ url_for('routes.user_posts', username=user.username, page=page_num) }}">
    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="var(--soft-primary)" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
        <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
    </svg>
    <small class="soft-primary-colour">Previous page</small>
</a>
{% endif %}
{% endif %}
{% endfor %}

<!-- NEXT -->
{% for page_num in posts.iter_pages(left_edge=0, right_edge=0, left_current=1, right_current=2) %}
{% if page_num and page_num > posts.page %}
{% if page_num > posts.page %}
<a class="soft-primary-colour float-right mb-3" href="{{ url_for('routes.user_posts', username=user.username, page=page_num) }}">
    <small class="soft-primary-colour">Next page</small>
    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="var(--soft-primary)" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z" />
        <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z" />
    </svg>
</a>
{% endif %}
{% endif %}
{% endfor %}

<!-- CONTENT END -->
{% endblock content %}

<!-- SIDEBAR START -->
{% block sidebar %}

<div class="col-md-5">
    <div class="content-section">
        <div class="align-middle mt-1">
            <h5 class="heading-title">All posts by: @{{ user.username }}</h5>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#3f3fff" class="bi bi-clock-history mb-1" viewBox="0 0 16 16">
                <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z" />
                <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z" />
                <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z" />
            </svg>
        </div>
        <ul class="list-group">

            <!-- LINK #1 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Total posts: {{ posts.total }}
                </li>
            </a>

            <!-- LINK #2 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Mauris et turpis ornare, eleifend sem ac, auctor sem.
                </li>
            </a>

            <!-- LINK #3 -->
            <a href="#">
                <li class="sidebar-list d-flex justify-content-between align-items-center">
                    Vivamus ut mauris nec tortor semper fringilla scelerisque a diam.
                </li>
            </a>

        </ul>
        </p>
    </div>
</div>

<!-- SIDEBAR END -->
{% endblock sidebar %}